import type { QueryHookOptions } from '@apollo/client';
import { gql, useQuery } from '@apollo/client';
import { Button, OrderIcon, ResourceIcon } from '@bibliotheca-dao/ui-lib';
import { useState } from 'react';
import { OrdersFilter } from '@/components/filters/OrdersFilter';
import { RarityFilter } from '@/components/filters/RarityFilter';
import { ResourcesFilter } from '@/components/filters/ResourcesFilter';
import { TraitsFilter } from '@/components/filters/TraitsFilter';
import type {
  QueryGetRealmsArgs,
  GetRealmsQuery,
  RealmFragmentFragment,
  ResourceType,
  OrderType,
} from '@/generated/graphql';
import { RealmFragmentFragmentDoc } from '@/generated/graphql';
import { useUIContext } from '@/hooks/useUIContext';
import { useWalletContext } from '@/hooks/useWalletContext';

// TODO: why this is not generated by codegen?
function useRealmsQueryWithArgs(
  options: QueryHookOptions<GetRealmsQuery, QueryGetRealmsArgs>
) {
  const GetRealmsDocument = gql`
    query getRealms(
      $filter: RealmFilterInput
      $orderBy: RealmOrderByInput
      $take: Float
      $skip: Float
    ) @api(name: starkIndexer) {
      getRealms(filter: $filter, orderBy: $orderBy, take: $take, skip: $skip) {
        ...RealmFragment
      }
    }
    ${RealmFragmentFragmentDoc}
  `;
  return useQuery<GetRealmsQuery, QueryGetRealmsArgs>(
    GetRealmsDocument,
    options
  );
}

export function RealmOverview() {
  const testRealm = {
    name: 'Smutmum',
    order: 'anger',
    id: 1,
    resources: ['Wood', 'DragonHide', 'Coal', 'Ruby', 'Copper'],
    statistics: ['Happiness', 'Culture', 'Food', 'Population'],
    military: ['Offence', 'Defence', 'Last Attacked'],
  };
  const { toggleMenuType, selectedMenuType, setSelectedId } = useUIContext();

  const { account, isConnected, displayName } = useWalletContext();

  const [filters, setFilters] = useState({
    rarity: {
      rarityScore: 0,
      rarityRank: 0,
    },
    traits: {
      region: 0,
      city: 0,
      harbour: 0,
      river: 0,
    },
    selectedOrders: [] as OrderType[],
    selectedResources: [] as ResourceType[],
  });

  const variables: QueryGetRealmsArgs = {
    filter: {
      rarityRank: {
        gte: filters.rarity.rarityRank,
      },
      rarityScore: {
        gte: filters.rarity.rarityScore,
      },
      orderType:
        filters.selectedOrders.length > 0
          ? {
              in: [...filters.selectedOrders],
            }
          : undefined,
      AND: filters.selectedResources.map((resource) => ({
        resourceType: { equals: resource },
      })),
    },
  };

  const { data } = useRealmsQueryWithArgs({
    variables,
  });

  const openRealmDetails = (realmId: number) => {
    setSelectedId(realmId.toString());
    if (selectedMenuType !== 'realm') {
      toggleMenuType('realm');
    }
  };
  return (
    <div>
      <div className="flex justify-between">
        <div>Search</div>
        <div className="flex mb-4">
          <ResourcesFilter
            selectedValues={filters.selectedResources}
            onChange={(values) => {
              setFilters({ ...filters, selectedResources: [...values] });
            }}
          />
          <RarityFilter
            rarity={filters.rarity}
            onChange={(value) => {
              setFilters({ ...filters, rarity: { ...value } });
            }}
          />
          <OrdersFilter
            selectedValues={filters.selectedOrders}
            onChange={(values) => {
              setFilters({ ...filters, selectedOrders: [...values] });
            }}
          />
          <TraitsFilter
            traits={filters.traits}
            onChange={(value) => {
              setFilters({ ...filters, traits: { ...value } });
            }}
          />
        </div>
      </div>
      {data &&
        data.getRealms
          .slice(0, 10)
          .map((realm: RealmFragmentFragment, index) => (
            <div
              key={index}
              className="flex w-full h-auto max-w-full mb-4 overflow-x-scroll border border-gray-500 border-double rounded shadow-md justify-evenly"
            >
              <div className="flex w-full p-8 text-gray-800 rounded-l bg-white/70">
                <OrderIcon
                  className="self-center"
                  size={'md'}
                  order={realm.orderType}
                />
                <div className="self-center pl-6">
                  <h5 className="text-gray-400">{realm.realmId}</h5>
                  <h2 className="mb-3">{realm.name}</h2>
                </div>
              </div>
              <div className="w-full p-6 bg-black/70">
                {realm.resources?.map((resource, index) => {
                  return (
                    <div className="flex my-4 font-bold " key={index}>
                      <ResourceIcon size="sm" resource={resource.type} />{' '}
                      <span className="ml-4 uppercase tracking-veryWide">
                        {resource.type}
                      </span>
                      <span className="self-end px-4 ml-auto uppercase tracking-veryWide">
                        100
                      </span>
                    </div>
                  );
                })}
              </div>
              <div className="w-full p-8 bg-gray-800/70">
                {' '}
                {realm.traits?.map((trait, index) => {
                  return (
                    <div className="flex my-4 font-bold " key={index}>
                      <span className="ml-4 uppercase tracking-veryWide">
                        {trait.type}
                      </span>
                      <span className="self-end px-4 ml-auto uppercase tracking-veryWide">
                        {trait.qty}
                      </span>
                    </div>
                  );
                })}
              </div>
              <div className="w-full p-8 bg-gray-700/70">
                {' '}
                {testRealm.military.map((a, index) => {
                  return (
                    <div className="flex my-4 font-bold " key={index}>
                      <span className="uppercase tracking-veryWide">{a}</span>
                      <span className="self-end px-4 ml-auto uppercase tracking-veryWide">
                        100
                      </span>
                    </div>
                  );
                })}
              </div>
              <div className="flex flex-col justify-center w-full p-8 space-y-3 bg-gray-600/70">
                {' '}
                <Button variant="default" className="w-full uppercase">
                  fly to
                </Button>
                <Button
                  onClick={() => openRealmDetails(realm.realmId)}
                  variant="default"
                  className="w-full uppercase"
                >
                  details
                </Button>
              </div>
            </div>
          ))}
    </div>
  );
}
