import { Button } from '@bibliotheca-dao/ui-lib/base';
import { useStarknetTransactionManager } from '@starknet-react/core';
import Link from 'next/link';
import type { Status, TransactionStatus } from 'starknet';
import type { ENQUEUED_STATUS } from '@/constants/index';
import { getTxMessage } from '@/hooks/settling/useTxMessage';
import { ExternalLink } from '@/shared/Icons';

interface Metadata {
  description: string;
  title: string;
  action: string;
}
interface EnqueuedOrReceivedTransaction {
  metadata?: Metadata;
  status: Status | TransactionStatus | typeof ENQUEUED_STATUS;
  transactionHash?: string;
}
interface TxCartItem {
  transaction: EnqueuedOrReceivedTransaction;
  onRemove?: () => void;
}

const STYLES = {
  status: {
    REJECTED: 'bg-red-400',
    NOT_RECEIVED: 'bg-red-200',
    RECEIVED: 'bg-green-400/90 animate-pulse',
    PENDING: 'bg-orange-400 animate-pulse',
    ACCEPTED_ON_L2: 'bg-green-600/90',
    ACCEPTED_ON_L1: 'bg-green-900',
    TRANSACTION_RECEIVED: 'bg-green-400 animate-pulse',
    ENQUEUED: 'border-gray-600 border border-dashed',
  },
} as const;

export const TxCartItem = (props: TxCartItem) => {
  const { title, description } = getTxMessage(props.transaction);

  const resolvedTitle = props.transaction.metadata?.title || title;
  const resolvedMsg = props.transaction.metadata?.description || description;

  // Multicall descriptions are generated by the TransactionQueueContext
  // as array of objects that describe how to render sub-calls.
  const descriptionIsArray = Array.isArray(resolvedMsg);

  return (
    <div
      className={`${
        STYLES.status[props.transaction.status]
      }  rounded shadow-inner flex p-4 w-full font-semibold my-1`}
    >
      <div className="flex justify-between w-full p-4 rounded shadow-inner bg-black/10">
        <div>
          <h6 className="text-xs opacity-40">{props.transaction.status}</h6>
          <h2 className="sm:text-3xl opacity-80">{resolvedTitle}</h2>
          {descriptionIsArray ? (
            resolvedMsg.map((m, i) => {
              if (m.title && m.description) {
                return (
                  <div
                    className="py-2"
                    key={`${props.transaction.transactionHash}:${i}`}
                  >
                    <h5>
                      {i + 1}. {m.title}
                    </h5>
                    <p className="text-sm opacity-70">{m.description}</p>
                  </div>
                );
              }
              return <p key={i}>{m}</p>;
            })
          ) : (
            <p>{resolvedMsg}</p>
          )}
        </div>
        {props.transaction.transactionHash ? (
          <Link
            target={'_blank'}
            rel="noreferrer noopener"
            href={
              // TODO: use network aware link using @/util/blockExplorer
              'https://goerli.voyager.online/tx/' +
              props.transaction.transactionHash
            }
          >
            <a className="p-2 tracking-wide uppercase opacity-60">
              See on Voyager <ExternalLink className="inline-block w-4" />
            </a>
          </Link>
        ) : null}
        {props.onRemove && (
          <Button
            size="sm"
            variant="outline"
            texture={false}
            onClick={props.onRemove}
          >
            Remove
          </Button>
        )}
      </div>
      {/* <span>{props.transaction.lastUpdatedAt}</span> */}
    </div>
  );
};

export const TransactionCartTable = () => {
  const { transactions } = useStarknetTransactionManager();
  return (
    <div className="flex flex-col-reverse flex-wrap w-full">
      {transactions.map((a, index) => {
        return <TxCartItem key={index} transaction={a} />;
      })}
    </div>
  );
};
