# npm-check-updates configuration used by yarn deps:check && yarn deps:update
# convenience scripts.
# @link https://github.com/raineorshine/npm-check-updates

# Add here exclusions on packages if any
reject: [
    # execa (6.0.0 is esm and does not work with ts-jest)
    'execa',
    # Too early cause in esm
    'is-port-reachable',
    # Until get-starknet library merged https://github.com/apibara/starknet-react/pull/77
    '@argent/get-starknet',
  ]
