const troopList = [
  {
    name: 'Skirmisher',
    type: 'ranged',
    troopId: 1,
    tier: 1,
    agility: 2,
    attack: 7,
    armor: 2,
    vitality: 53,
    wisdom: 2,
  },
  {
    name: 'Longbow',
    type: 'ranged',
    tier: 2,
    troopId: 2,
    agility: 4,
    attack: 7,
    armor: 3,
    vitality: 53,
    wisdom: 3,
  },
  {
    name: 'Crossbow',
    type: 'ranged',
    tier: 3,
    troopId: 3,
    agility: 6,
    attack: 9,
    armor: 4,
    vitality: 53,
    wisdom: 4,
  },
  {
    name: 'Pikeman',
    type: 'melee',
    tier: 1,
    troopId: 4,
    agility: 7,
    attack: 4,
    armor: 5,
    vitality: 53,
    wisdom: 1,
  },

  {
    name: 'Knight',
    type: 'melee',
    tier: 2,
    troopId: 5,
    agility: 9,
    attack: 7,
    armor: 8,
    vitality: 79,
    wisdom: 2,
  },
  {
    name: 'Paladin',
    type: 'melee',
    tier: 3,
    troopId: 6,
    agility: 9,
    attack: 9,
    armor: 9,
    vitality: 106,
    wisdom: 3,
  },
  {
    name: 'Ballista',
    type: 'siege',
    tier: 1,
    troopId: 7,
    agility: 4,
    attack: 11,
    armor: 4,
    vitality: 53,
    wisdom: 2,
  },
  {
    name: 'Mangonel',
    type: 'siege',
    tier: 2,
    troopId: 8,
    agility: 4,
    attack: 10,
    armor: 5,
    vitality: 53,
    wisdom: 3,
  },
  {
    name: 'Trebuchet',
    type: 'siege',
    tier: 3,
    troopId: 9,
    agility: 4,
    attack: 12,
    armor: 6,
    vitality: 53,
    wisdom: 4,
  },
  {
    name: 'Apprentice',
    type: 'magic',
    tier: 1,
    troopId: 10,
    agility: 7,
    attack: 7,
    armor: 2,
    vitality: 53,
    wisdom: 8,
  },
  {
    name: 'Mage',
    type: 'magic',
    tier: 2,
    troopId: 11,
    agility: 7,
    attack: 9,
    armor: 2,
    vitality: 53,
    wisdom: 9,
  },
  {
    name: 'Arcanist',
    type: 'magic',
    tier: 3,
    troopId: 12,
    agility: 7,
    attack: 11,
    armor: 2,
    vitality: 53,
    wisdom: 10,
  },
];

export default troopList;
