const troopList = [
  {
    name: 'Watchman',
    type: 'melee',
    troopId: 1,
    tier: 1,
    agility: 1,
    attack: 1,
    defense: 3,
    vitality: 4,
    wisdom: 1,
  },
  {
    name: 'Guard',
    type: 'melee',
    tier: 2,
    troopId: 2,
    agility: 2,
    attack: 2,
    defense: 6,
    vitality: 8,
    wisdom: 2,
  },
  {
    name: 'Guard Captain',
    type: 'melee',
    tier: 3,
    troopId: 3,
    agility: 4,
    attack: 4,
    defense: 12,
    vitality: 16,
    wisdom: 4,
  },
  {
    name: 'Squire',
    type: 'melee',
    tier: 1,
    troopId: 4,
    agility: 1,
    attack: 4,
    defense: 1,
    vitality: 4,
    wisdom: 3,
  },

  {
    name: 'Knight',
    type: 'melee',
    tier: 2,
    troopId: 5,
    agility: 4,
    attack: 4,
    defense: 12,
    vitality: 16,
    wisdom: 4,
  },
  {
    name: 'Knight Commander',
    type: 'melee',
    tier: 3,
    troopId: 6,
    agility: 4,
    attack: 16,
    defense: 4,
    vitality: 4,
    wisdom: 12,
  },
  {
    name: 'Scout',
    type: 'Ranged',
    tier: 1,
    troopId: 7,
    agility: 4,
    attack: 3,
    defense: 1,
    vitality: 1,
    wisdom: 1,
  },
  {
    name: 'Archer',
    type: 'ranged',
    tier: 2,
    troopId: 8,
    agility: 8,
    attack: 6,
    defense: 2,
    vitality: 2,
    wisdom: 2,
  },
  {
    name: 'Sniper',
    type: 'ranged',
    tier: 3,
    troopId: 9,
    agility: 16,
    attack: 12,
    defense: 4,
    vitality: 4,
    wisdom: 4,
  },
  {
    name: 'Scorpio',
    type: 'Siege',
    tier: 1,
    troopId: 10,
    agility: 1,
    attack: 4,
    defense: 1,
    vitality: 3,
    wisdom: 1,
  },
  {
    name: 'Ballista',
    type: 'Siege',
    tier: 2,
    troopId: 11,
    agility: 2,
    attack: 8,
    defense: 2,
    vitality: 6,
    wisdom: 2,
  },
  {
    name: 'Catapult',
    type: 'Siege',
    tier: 3,
    troopId: 12,
    agility: 4,
    attack: 16,
    defense: 4,
    vitality: 12,
    wisdom: 4,
  },
  {
    name: 'Apprentice',
    type: 'ranged',
    tier: 1,
    troopId: 13,
    agility: 2,
    attack: 2,
    defense: 1,
    vitality: 1,
    wisdom: 4,
  },
  {
    name: 'Mage',
    type: 'ranged',
    tier: 2,
    troopId: 14,
    agility: 4,
    attack: 4,
    defense: 2,
    vitality: 2,
    wisdom: 8,
  },
  {
    name: 'Arcanist',
    type: 'ranged',
    tier: 3,
    troopId: 15,
    agility: 8,
    attack: 8,
    defense: 4,
    vitality: 4,
    wisdom: 16,
  },
  {
    name: 'GrandMarshal',
    type: 'ranged',
    tier: 3,
    troopId: 16,
    agility: 16,
    attack: 16,
    defense: 16,
    vitality: 16,
    wisdom: 16,
  },
];

export default troopList;
