/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/* eslint-disable react/no-unknown-property */

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Icosphere: THREE.Mesh;
    inner_gate001: THREE.Mesh;
    inner_gate002: THREE.Mesh;
    gate_north001: THREE.Mesh;
    gate_east001: THREE.Mesh;
    gate003: THREE.Mesh;
    gate_west001: THREE.Mesh;
    tower001: THREE.Mesh;
    tower001_1: THREE.Mesh;
    tower001_2: THREE.Mesh;
    tower001_3: THREE.Mesh;
    tower001_4: THREE.Mesh;
    tower001_5: THREE.Mesh;
    tower001_6: THREE.Mesh;
    tower001_7: THREE.Mesh;
    center001_1: THREE.Mesh;
    center001_2: THREE.Mesh;
    center001_3: THREE.Mesh;
    center001_4: THREE.Mesh;
    wall_inner_northeast001: THREE.Mesh;
    wall_inner_northwest001: THREE.Mesh;
    wall_inner_southeast001: THREE.Mesh;
    wall_inner_southwest001: THREE.Mesh;
    wall_outer_northeast001: THREE.Mesh;
    wall_outer_northwest001: THREE.Mesh;
    wall_outer_southeast001: THREE.Mesh;
    wall_outer_southwest001: THREE.Mesh;
    bridge001: THREE.Mesh;
    bridge005: THREE.Mesh;
    bridge003: THREE.Mesh;
    bridge007: THREE.Mesh;
    bridge002: THREE.Mesh;
    bridge006: THREE.Mesh;
    bridge004: THREE.Mesh;
    bridge008: THREE.Mesh;
  };
  materials: {
    Stone: THREE.MeshStandardMaterial;
    Shingles: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    '/bastion_exportTest2.glb'
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        scale={66.98}
      />
      <mesh
        geometry={nodes.inner_gate001.geometry}
        material={materials.Stone}
        position={[0, 14.7, 0]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.inner_gate002.geometry}
        material={materials.Stone}
        position={[0, 14.7, 0]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      />
      <mesh
        geometry={nodes.gate_north001.geometry}
        material={materials.Stone}
        position={[0, -99.35, 0]}
      />
      <mesh
        geometry={nodes.gate_east001.geometry}
        material={materials.Stone}
        position={[0, -99.35, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.gate003.geometry}
        material={materials.Stone}
        position={[0, -99.35, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.gate_west001.geometry}
        material={materials.Stone}
        position={[0, -99.35, 0]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <group position={[0, -75.11, 0]}>
        <mesh geometry={nodes.tower001.geometry} material={materials.Stone} />
        <mesh
          geometry={nodes.tower001_1.geometry}
          material={materials.Shingles}
        />
      </group>
      <group position={[0, -75.11, 0]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.tower001_2.geometry} material={materials.Stone} />
        <mesh
          geometry={nodes.tower001_3.geometry}
          material={materials.Shingles}
        />
      </group>
      <group position={[0, -75.11, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.tower001_4.geometry} material={materials.Stone} />
        <mesh
          geometry={nodes.tower001_5.geometry}
          material={materials.Shingles}
        />
      </group>
      <group position={[0, -75.11, 0]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.tower001_6.geometry} material={materials.Stone} />
        <mesh
          geometry={nodes.tower001_7.geometry}
          material={materials.Shingles}
        />
      </group>
      <group position={[0, 7.97, 0]} rotation={[0, Math.PI / 4, 0]}>
        <mesh
          geometry={nodes.center001_1.geometry}
          material={materials.Stone}
        />
        <mesh
          geometry={nodes.center001_2.geometry}
          material={materials.Shingles}
        />
      </group>
      <group
        position={[0, 7.97, 0]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      >
        <mesh
          geometry={nodes.center001_3.geometry}
          material={materials.Stone}
        />
        <mesh
          geometry={nodes.center001_4.geometry}
          material={materials.Shingles}
        />
      </group>
      <mesh
        geometry={nodes.wall_inner_northeast001.geometry}
        material={materials.Stone}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.wall_inner_northwest001.geometry}
        material={materials.Stone}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.wall_inner_southeast001.geometry}
        material={materials.Stone}
        rotation={[Math.PI, -Math.PI / 4, Math.PI]}
      />
      <mesh
        geometry={nodes.wall_inner_southwest001.geometry}
        material={materials.Stone}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      />
      <mesh
        geometry={nodes.wall_outer_northeast001.geometry}
        material={materials.Stone}
        rotation={[0, -Math.PI / 4, 0]}
        scale={1.06}
      />
      <mesh
        geometry={nodes.wall_outer_northwest001.geometry}
        material={materials.Stone}
        rotation={[0, Math.PI / 4, 0]}
        scale={1.06}
      />
      <mesh
        geometry={nodes.wall_outer_southeast001.geometry}
        material={materials.Stone}
        rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        scale={1.06}
      />
      <mesh
        geometry={nodes.wall_outer_southwest001.geometry}
        material={materials.Stone}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={1.06}
      />
      <mesh
        geometry={nodes.bridge001.geometry}
        material={materials.Stone}
        position={[0, -1.36, 0]}
      />
      <mesh
        geometry={nodes.bridge005.geometry}
        material={materials.Stone}
        position={[-0.35, -1.36, 0.77]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.bridge003.geometry}
        material={materials.Stone}
        position={[-0.74, -1.36, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.bridge007.geometry}
        material={materials.Stone}
        position={[-0.35, -1.36, -1.47]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.bridge002.geometry}
        material={materials.Stone}
        position={[-16.39, -1.36, 0]}
      />
      <mesh
        geometry={nodes.bridge006.geometry}
        material={materials.Stone}
        position={[-0.35, -1.36, -15.62]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.bridge004.geometry}
        material={materials.Stone}
        position={[15.65, -1.36, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.bridge008.geometry}
        material={materials.Stone}
        position={[-0.35, -1.36, 14.92]}
        rotation={[0, 1.57, 0]}
      />
    </group>
  );
}

useGLTF.preload('/bastion_exportTest2.glb');
