/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Artbake Graphics (https://sketchfab.com/ismir)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/medieval-castle-with-village-5109b5e46e064790badecedf8f6d2ef6
title: Medieval castle with village
*/

/* eslint-disable react/no-unknown-property */

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
  };
  materials: {
    ['black.037']: THREE.MeshStandardMaterial;
    pink: THREE.MeshStandardMaterial;
    ['FrontColor.002']: THREE.MeshStandardMaterial;
    ['gray.067']: THREE.MeshStandardMaterial;
    ['black.037_0']: THREE.MeshStandardMaterial;
    ['blue.016']: THREE.MeshStandardMaterial;
    ['brick.006']: THREE.MeshStandardMaterial;
    ['brown.086']: THREE.MeshStandardMaterial;
    ['brown.086_0']: THREE.MeshStandardMaterial;
    ['dirt.001']: THREE.MeshStandardMaterial;
    ['dirtroad.003']: THREE.MeshStandardMaterial;
    ['dkbrown.025']: THREE.MeshStandardMaterial;
    ['dkbrown.025_0']: THREE.MeshStandardMaterial;
    ['dkgreen.016']: THREE.MeshStandardMaterial;
    ['gray.067_0']: THREE.MeshStandardMaterial;
    ['grass.013']: THREE.MeshStandardMaterial;
    ['gray.059']: THREE.MeshStandardMaterial;
    ['gray.067_1']: THREE.MeshStandardMaterial;
    ['green.002']: THREE.MeshStandardMaterial;
    ['litblue.002']: THREE.MeshStandardMaterial;
    ['ltgray.030']: THREE.MeshStandardMaterial;
    ['red.006']: THREE.MeshStandardMaterial;
    ['schingle.007']: THREE.MeshStandardMaterial;
    ['skincolr.001']: THREE.MeshStandardMaterial;
    ['smlstone.043']: THREE.MeshStandardMaterial;
    ['smlstone.043_0']: THREE.MeshStandardMaterial;
    ['tile.009']: THREE.MeshStandardMaterial;
    ['gray.067_2']: THREE.MeshStandardMaterial;
    ['trubrown.024']: THREE.MeshStandardMaterial;
    ['white.025']: THREE.MeshStandardMaterial;
    ['white.025_0']: THREE.MeshStandardMaterial;
    ['window.008']: THREE.MeshStandardMaterial;
    ['wood.045']: THREE.MeshStandardMaterial;
    ['yellow.007']: THREE.MeshStandardMaterial;
    ['yellwhit.015']: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    '/medieval_castle_with_village.glb'
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['black.037']}
        />
        <mesh geometry={nodes.Object_3.geometry} material={materials.pink} />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials['FrontColor.002']}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials['gray.067']}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['black.037_0']}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials['blue.016']}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials['brick.006']}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials['brown.086']}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials['brown.086']}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials['brown.086_0']}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials['dirt.001']}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials['dirtroad.003']}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials['dkbrown.025']}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials['dkbrown.025_0']}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials['dkgreen.016']}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials['gray.067_0']}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials['grass.013']}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials['gray.059']}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials['gray.067_1']}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials['green.002']}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials['litblue.002']}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials['ltgray.030']}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials['red.006']}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials['schingle.007']}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials['skincolr.001']}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials['skincolr.001']}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials['smlstone.043']}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials['smlstone.043_0']}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials['tile.009']}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials['gray.067_2']}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials['trubrown.024']}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials['white.025']}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials['white.025_0']}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials['window.008']}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials['wood.045']}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials['yellow.007']}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials['yellwhit.015']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/medieval_castle_with_village.glb');
