/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/* eslint-disable react/no-unknown-property */

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['2k']: THREE.Mesh;
    followers: THREE.Mesh;
    ['thank-you']: THREE.Mesh;
    Rocks: THREE.Mesh;
    Grid001: THREE.Mesh;
    Grid001_1: THREE.Mesh;
    Floor: THREE.Mesh;
  };
  materials: {
    White2K: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    ['Rocks.001']: THREE.MeshStandardMaterial;
    ['TreeGreen.003']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    Floor: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<any>();
  const { nodes, materials } = useGLTF('/starter-scene.glb') as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['2k'].geometry}
        material={materials.White2K}
        position={[-1.75, 2.73, -0.7]}
        rotation={[0, Math.PI / 2, 0]}
        scale={24.87}
      />
      <mesh
        geometry={nodes.followers.geometry}
        material={materials.White}
        position={[7.2, 0.69, 5.24]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.7}
      />
      <mesh
        geometry={nodes['thank-you'].geometry}
        material={materials.White}
        position={[9.73, 0.25, 2.79]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.61}
      />
      <mesh
        geometry={nodes.Rocks.geometry}
        material={materials['Rocks.001']}
        position={[0.83, 1.01, 3.83]}
        scale={[0.83, 1.51, 11.35]}
      />
      <mesh
        geometry={nodes.Grid001.geometry}
        material={materials['TreeGreen.003']}
      />
      <mesh
        geometry={nodes.Grid001_1.geometry}
        material={materials['Material.004']}
      />
      <mesh geometry={nodes.Floor.geometry} material={materials.Floor} />
    </group>
  );
}

useGLTF.preload('/starter-scene.glb');
