name: CI-monorepo-integrity

on:
  push:
    branches:
      - dev
      - monorepo
      - main
    paths:
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Why not using setup-node 2.2+ cache option (yet) ?
      # see https://github.com/belgattitude/nextjs-monorepo-example/pull/369
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Check for duplicate dependencies in lock file
        run: |
          yarn dedupe --check

      - name: Check for yarn constraints.pro
        run: |
          yarn constraints

      - name: Check monorepo dependency graph
        run: |
          yarn check:install
